export const TEMP_NEEDS_DATA = [
  {
    job: "Svetsare",
    municipality: "Pedersöre",
    image: "/ai1.webp",
    isNew: true,
    duration: "Tills vidare",
    balance: 2,
  },
  {
    job: "Fotograf",
    municipality: "Nykarleby",
    image: "/ai2.webp",
    isNew: false,
    duration: "3 månader",
    balance: 1,
    type: "supply",
  },
  {
    job: "CNC-operatör",
    municipality: "Kronoby",
    image: "/ai3.webp",
    isNew: false,
    duration: "6 månader",
    balance: -1,
  },
  {
    job: "C++ programmerare",
    municipality: "Jakobstad",
    image: "/ai4.webp",
    isNew: false,
    duration: "Tills vidare",
    balance: -1,
  },
  {
    job: "Laminerare",
    municipality: "Larsmo",
    image: "/ai5.webp",
    isNew: false,
    duration: "Under sommaren",
    balance: -3,
  },
  {
    job: "TIG-svetsare",
    municipality: "Nykarleby",
    image: "/ai6.webp",
    isNew: false,
    duration: "Tills vidare",
    balance: 2,
  },
  {
    job: "Grafisk designer",
    municipality: "Kronoby",
    image: "/ai7.webp",
    isNew: false,
    duration: "Under året",
    balance: 1,
  },
  {
    job: "Elektriker",
    municipality: "Jakobstad",
    image: "/ai8.webp",
    isNew: false,
    duration: "Under året",
    balance: 1,
  },
  {
    job: "Grävmaskinsförare",
    municipality: "Nykarleby",
    image: "/ai9.webp",
    isNew: true,
    duration: "Under året",
    balance: 1,
  },
  {
    job: "C# programmerare",
    municipality: "Jakobstad",
    image: "/ai10.webp",
    isNew: false,
    duration: "Tills vidare",
    balance: 1,
  },
  {
    job: "Montör",
    municipality: "Kronoby",
    image: "/ai11.webp",
    isNew: true,
    duration: "Tills vidare",
    balance: -2,
  },
  {
    job: "Paketbilsförare",
    municipality: "Larsmo",
    image: "/ai12.webp",
    isNew: false,
    duration: "Under sommaren",
    balance: -4,
  },
].map((nd, i) => ({ ...nd, id: i.toString() }))
